// This file was autogenerated by closure/bin/build/closurebuilder.py.
// Please do not edit.
(function () {
	var hasOwnProperty = Object.prototype.hasOwnProperty;
	var hasOwn = function (obj, key) {
		return hasOwnProperty.call(obj, key);
	};
	var host = '/*host*/';
	var relUrlMap = {
		/*urlMap*/
	};
	var alias = {};
	for (var key in relUrlMap) {
		if (hasOwn(relUrlMap, key)) {
			alias[key] = host + relUrlMap[key];
		}
	}
	window['_moduleConfig'] = {alias: alias};
})();
/*moduleJs*/
_mytouchConfig = {"index": ["/*entryPointModule*/", "init"], "containerId": "businessContent"};
setTimeout(function () {
	modulejs(["/*entryPointModule*/"], function (m) {
	});
}, 10);